### ISSUE TITLE
Parse Server providers - list too short?

### ISSUE THREAD

**Issue by ojosdegris** [relatedcode/ParseAlternatives#140]
Hi, I find this list to be really useful, however I have question about last section. Why does it only mention gaps and bluemix? Both aws and azure as well as triton, rackspace, digital ocean, linode and many others allow you to host node.js app and either offer easy way to setup mongo, or use mongolab.

**Comment by relatedcode** [comment]
You are free to insert any of these new providers to the list. Thank you for your cooperation. :)
