### ISSUE TITLE
Torii.js 

### ISSUE THREAD

**Issue by matteocrippa** [relatedcode/ParseAlternatives#162]
I'd prefer not to make a pull at the beginning, but I want to notify you the presence of OSS tool I developed so far that acts as BAAS, [torii.js](https://github.com/toriijs/torii.js)

Feel free to consider to add it to the list, a new improved version is in the roadmap.

**Comment by matteocrippa** [comment]
not eligible?

**Comment by relatedcode** [comment]
@matteocrippa Please make a pull request. Thanks!
