### ISSUE TITLE
Survivability

### ISSUE THREAD

**Issue by rthurimella** [relatedcode/ParseAlternatives#2]
Having got burnt by Parse shutting down, and noticing that StackMob also closed its doors recently, one of the criteria for a choosing a BaaS provider should be whether they will be around for the long haul. Just a long list of alternatives is of little help for someone looking to migrate from Parse.

**Comment by sidan5** [comment]
+1

**Comment by Burnsoft** [comment]
is helios already dead?

**Comment by temitope** [comment]
+1

**Comment by relatedcode** [comment]
Discussed. :)
