### ISSUE TITLE
Device Push Notifications

### ISSUE THREAD

**Issue by DevicePush** [relatedcode/ParseAlternatives#273]
**Device Push Notifications** opens the doors to all developers who want to implement notifications in their apps.

**Device Push Notifications** is a service that consists of SDKs, API, and a control panel to manage notifications without having to deal with the different platforms, unifying all the code. With Device Push Notifications, you will save much time and no need to worry about storing large token, Device Push Notifications will do it all for you.

We know that push notifications are not everything when it comes to having a communication with mobile applications, so our effort not only be focused on this event, but we will go activating improvements which will allow the implementation kinds of events such as music, interactive maps, videos, or surveys, among other…

**Comment by relatedcode** [comment]
@DevicePush Please create a pull request. Thanks!
