### ISSUE TITLE
Page Organization

### ISSUE THREAD

**Issue by adonoho** [relatedcode/ParseAlternatives#81]
Gentlefolk,

I note that the folks offering running Parse Server are last on the list. IMO, as they provide the fastest path to migration of most Parse developers, they should be first on the list. Followed by the folks offering missing Parse services, such as push notification services or in-app purchase receipt validation.

Only after the folks focussing upon making the transition as simple as possible should the other vendors appear.

IMO, Parse was a very weak provider of analytics. None of my clients would use them. I suspect most Parse developers did not use them either. Perhaps it is a useful to provide a list of mobile analytics services. But I suspect it is already amply covered elsewhere.

Disclosure: I am financially uninvolved with any of the vendors currently listed. In my consulting practice, I've been known to use Couchbase. Many years ago, 7+, I worked for one of the vendors on this list, IBM.

Anon,
Andrew

**Comment by relatedcode** [comment]
Thanks Andrew! Will be considered to reorder the list. :)
